[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
fallible = { path = "../fallible" }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }

[features]
fallible-sim = ["fallible/fallible-sim"]